version: "3"
services:
  palworld:
    container_name: palworld
    image: standwithccp/palworld:latest
    volumes:
      - ${SAVE_PATH}:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    restart: always
    environment:
      TZ: ${TZ}
    healthcheck:
      test: |
        memcheck.bash ${AdminPassword}
      interval: 300s
      retries: 5
      start_period: 20s
      timeout: 5s